BreachAchievements = BreachAchievements || {}
BreachAchievements.AchievementTable = {

	{
		name = "tester",
		achievements_name = "Участник ЗБТ",
		desc = "Примите участие во втором ЗБТ UTOPIA",
		image = "kissing_boys/bk_soft_kiss_icon.png",
		secret = true,
		countable = false,
		countnum = 0,
		giveatendround = false,
		awardexp = 100,
		textnotify = true,
	},

	{
		name = "scp_chair",
		achievements_name = "ДАЙТЕ ЕМУ СТУЛ!!!",
		desc = "Умрите от обыкновенного стула",
		image = "nextoren/achievements/ahive36.jpg",
		secret = true,
		countable = false,
		countnum = 0,
		giveatendround = false,
		awardexp = 100,
		textnotify = true,
	},

	{
		name = "halloween",
		achievements_name = "Halloween 2025",
		desc = "spooky",
		image = "nextoren/achievements/halloween.png",
		secret = true,
		mega = true,
		countable = false,
		countnum = 0,
		giveatendround = false,
		awardexp = 100,
		textnotify = true,
	},

	{
		name = "antifurry",
		achievements_name = "Сильнейший среди пушистых",
		desc = "Победи в редчайшем ивенте за выживших",
		image = "nextoren/achievements/antifurry.png",
		secret = true,
		mega = true,
		countable = false,
		countnum = 0,
		giveatendround = false,
		awardexp = 100,
		textnotify = true,
	},

	{
		name = "xmas2025",
		achievements_name = "Новый год 2025",
		desc = "Примите участие в спасении Нового года в конце 2025",
		image = "nextoren/achievements/christmas.png",
		secret = true,
		mega = true,
		countable = false,
		countnum = 0,
		giveatendround = false,
		awardexp = 100,
		textnotify = true,
	},
	
	{
		name = "wrongescape",
		achievements_name = "Ошибся дорогой",
		desc = "Успешно сбегите за\nКласс-Д/ШДЗ через вертолет.",
		image = "nextoren/achievements/ahive33.jpg",
		secret = false,
		countable = false,
		countnum = 0,
		giveatendround = false,
		awardexp = 100,
		textnotify = true,
	},

	{
		name = "shaky",
		achievements_name = "Уникальный",
		desc = "Если у вас ачивка есть, значит шаки так решил",
		image = "nextoren/achievements/ahive3.jpg",
		secret = true,
		countable = false,
		countnum = 0,
		giveatendround = false,
		awardexp = 100,
		textnotify = true,
	},

	{
		name = "headshot",
		achievements_name = "В яблочко!",
		desc = "Убейте человека в голову",
		image = "nextoren/achievements/ahive51.jpg",
		secret = false,
		countable = false,
		countnum = 0,
		giveatendround = false,
		awardexp = 100,
		textnotify = true,
	},

	{
		name = "fallkill",
		achievements_name = "Кавабанга!",
		desc = "Убейте человека, падаю ему на голову",
		image = "nextoren/achievements/ahive89.jpg",
		secret = true,
		countable = false,
		countnum = 0,
		giveatendround = false,
		awardexp = 100,
		textnotify = true
	},

	{
		name = "cheemer",
		achievements_name = "Лучший друг человека",
		desc = "Сбегите вместе с чимсом",
		image = "nextoren/achievements/ahive3.jpg",
		secret = true,
		countable = false,
		countnum = 0,
		giveatendround = false,
		awardexp = 100,
		textnotify = true
	},

	{
		name = "firsttime",
		achievements_name = "Впервые",
		desc = "Зайдите на сервер",
		image = "nextoren/achievements/ahive128.jpg",
		secret = false,
		countable = false,
		countnum = 0,
		giveatendround = false,
		awardexp = 0,
		textnotify = true,
	},

	{
		name = "lucky",
		achievements_name = "Везунчик",
		desc = "Стать поддержкой 2 раза подряд",
		image = "nextoren/achievements/ahive128.jpg",
		secret = true,
		countable = false,
		countnum = 0,
		giveatendround = false,
		awardexp = 0,
		textnotify = true,
	},

	{
		name = "scp409",
		achievements_name = "Довольно прохладно...",
		desc = "Превратитесь в статую 409",
		image = "nextoren/achievements/ahive78.jpg",
		secret = true,
		countable = false,
		countnum = 0,
		giveatendround = false,
		awardexp = 0,
		textnotify = true,
	},

	{
		name = "secretword",
		achievements_name = "Секретное слово",
		desc = "",
		image = "nextoren/achievements/ahive52.jpg",
		secret = true,
		countable = false,
		countnum = 0,
		giveatendround = false,
		awardexp = 0,
		textnotify = true,
	},

	{
		name = "chaosradio",
		achievements_name = "Ты идешь с нами.",
		desc = "Сбегите через РПХ.",
		image = "nextoren/achievements/ahive105.jpg",
		secret = true,
		countable = false,
		countnum = 0,
		giveatendround = false,
		awardexp = 0,
		textnotify = true,
	},

	{
		name = "car",
		achievements_name = "Поехали!",
		desc = "Сбегите с помощью машины.",
		image = "nextoren/achievements/ahive115.jpg",
		secret = true,
		countable = false,
		countnum = 0,
		giveatendround = false,
		awardexp = 0,
		textnotify = true,
	},

	{
		name = "carportal",
		achievements_name = "Потеря дорогостоещего оборудования",
		desc = "Сбегите через портал ДЗ на машине..",
		image = "nextoren/achievements/ahive115.jpg",
		secret = true,
		countable = false,
		countnum = 0,
		giveatendround = false,
		awardexp = 0,
		textnotify = true,
	},

	{
		name = "comitee",
		achievements_name = "Комитет Человечности",
		desc = "Используйте способность\nинспектора по этике 5 раз",
		image = "nextoren/achievements/ahive101.jpg",
		secret = false,
		countable = true,
		countnum = 5,
		giveatendround = false,
		awardexp = 100,
		textnotify = true,
	},

	{
		name = "scp005",
		achievements_name = "Волшебный ключик",
		desc = "Откройте дверь с помощью\nSCP-005",
		image = "nextoren/achievements/ahive16.jpg",
		secret = false,
		countable = false,
		countnum = 0,
		giveatendround = false,
		awardexp = 100,
		textnotify = true,
	},

	{
		name = "scarlet",
		achievements_name = "Дитё Алого Короля",
		desc = "Призвать Алого Короля",
		image = "nextoren/achievements/ahive121.jpg",
		secret = false,
		countable = false,
		countnum = 0,
		giveatendround = false,
		awardexp = 100,
		textnotify = true,
	},


	{
		name = "bigboom",
		achievements_name = "Теория большего взрыва",
		desc = "Активировать боеголовку и взорвать ее",
		image = "nextoren/achievements/ahive36.jpg",
		secret = true,
		countable = false,
		countnum = 0,
		giveatendround = false,
		awardexp = 100,
		textnotify = true,
	},

	{
		name = "monorail",
		achievements_name = "Рельсы под напряжением",
		desc = "сбежать на монорельсе",
		image = "nextoren/achievements/ahive54.jpg",
		secret = false,
		countable = false,
		countnum = 0,
		giveatendround = false,
		awardexp = 100,
		textnotify = true,
	},

	{
		name = "escape",
		achievements_name = "Комплекс чудес",
		desc = "сбежать из комплекса",
		image = "nextoren/achievements/ahive125.jpg",
		secret = false,
		countable = false,
		countnum = 0,
		giveatendround = false,
		awardexp = 100,
		textnotify = true,
	},

	{
		name = "escapehand",
		achievements_name = "Рука помощи",
		desc = "сбежать с помощью руки",
		image = "nextoren/achievements/ahive134.jpg",
		secret = true,
		countable = false,
		countnum = 0,
		giveatendround = false,
		awardexp = 100,
		textnotify = true,
	},

	{
		name = "apcescape",
		achievements_name = "Тяжелая кавалерия",
		desc = "сбежать на бтр",
		image = "nextoren/achievements/ahive118.jpg",
		secret = true,
		countable = false,
		countnum = 0,
		giveatendround = false,
		awardexp = 100,
		textnotify = true,
	},

	{
		name = "scp0492",
		achievements_name = "Я излечился",
		desc = "стать жертвой SCP-049",
		image = "nextoren/achievements/ahive138.jpg",
		secret = false,
		countable = false,
		countnum = 0,
		giveatendround = false,
		awardexp = 100,
		textnotify = true,
	},

	{
		name = "beglec",
		achievements_name = "Беглец",
		desc = "Побег через калитку",
		image = "nextoren/achievements/ahive104.jpg",
		secret = true,
		countable = false,
		countnum = 0,
		giveatendround = false,
		awardexp = 100,
		textnotify = true,
	},

	{
		name = "fbiescape",
		achievements_name = "Миссия невыполнима",
		desc = "Сбежать со взломанными компами",
		image = "nextoren/achievements/ahive45.jpg",
		secret = false,
		countable = false,
		countnum = 0,
		giveatendround = false,
		awardexp = 100,
		textnotify = true,
	},

	{
		name = "tnt",
		achievements_name = "Проект Манхэттен",
		desc = "использовать тнт в кофейном автомате",
		image = "nextoren/achievements/ahive56.jpg",
		secret = true,
		countable = false,
		countnum = 0,
		giveatendround = false,
		awardexp = 100,
		textnotify = true,
	},

	{
		name = "gauss",
		achievements_name = "Фенрир",
		desc = "Получить гаусс пушку",
		image = "nextoren/achievements/ahive91.jpg",
		secret = false,
		countable = false,
		countnum = 0,
		giveatendround = false,
		awardexp = 100,
		textnotify = true,
	},

	{
		name = "secrettoy",
		achievements_name = "Найди меня если сможешь",
		desc = "Найдите секретную игрушку",
		image = "nextoren/achievements/ahive3.jpg",
		secret = true,
		countable = false,
		countnum = 0,
		giveatendround = false,
		awardexp = 100,
		textnotify = true,
	},

	{
		name = "scp049",
		achievements_name = "Пир во время чумы",
		desc = "Сделать 5 зомби за scp-049",
		image = "nextoren/achievements/ahive70.jpg",
		secret = false,
		countable = true,
		countnum = 5,
		giveatendround = false,
		awardexp = 100,
		textnotify = true,
	},

	{
		name = "married",
		achievements_name = "Молодожены",
		desc = "Побывать на свадьбе Пузырика и Императора",
		image = "nextoren/achievements/ahive129.jpg",
		secret = true,
		mega = true,
		countable = false,
		countnum = 0,
		giveatendround = false,
		awardexp = 100,
		textnotify = true,
	},

	{
		name = "kutarum_hb",
		achievements_name = "День рождения Кутарума",
		desc = "Побывать на ДР Кутарума",
		image = "nextoren/achievements/ahive12.jpg",
		secret = true,
		mega = true,
		countable = false,
		countnum = 0,
		giveatendround = false,
		awardexp = 100,
		textnotify = true,
	},

	{
		name = "donater",
		achievements_name = "Покупной",
		desc = "Купите много всего",
		image = "nextoren/achievements/ahive73.jpg",
		secret = true,
		countable = false,
		countnum = 0,
		giveatendround = false,
		awardexp = 100,
		textnotify = true,
	},

	{
		name = "usa",
		achievements_name = "Демократия превыше всего",
		desc = "Выйграть за США",
		image = "nextoren/achievements/ahive111.jpg",
		secret = false,
		countable = false,
		countnum = 0,
		giveatendround = false,
		awardexp = 100,
		textnotify = true,
	},

	{
		name = "nazi",
		achievements_name = "Марш за фюрера",
		desc = "Выйграть за Третий Рейх",
		image = "nextoren/achievements/ahive15.jpg",
		secret = false,
		countable = false,
		countnum = 0,
		giveatendround = false,
		awardexp = 100,
		textnotify = true,
	},

	{
		name = "combine",
		achievements_name = "Коллаборацианист",
		desc = "Работая командой убейте Гордона Фримена",
		image = "nextoren/achievements/ahive147.jpg",
		secret = false,
		countable = false,
		countnum = 0,
		giveatendround = false,
		awardexp = 100,
		textnotify = true,
	},

	{
		name = "uiugoc",
		achievements_name = "Настоящий рыцарь",
		desc = "Убейте всех поддельных рыцарей",
		image = "nextoren/achievements/ahive12.jpg",
		secret = false,
		countable = false,
		countnum = 0,
		giveatendround = false,
		awardexp = 100,
		textnotify = true,
	},

	{
		name = "gf",
		achievements_name = "Физик Теоретик",
		desc = "Убить всех комбайнов будучи Гордоном Фрименем",
		image = "nextoren/achievements/ahive81.jpg",
		secret = false,
		countable = false,
		countnum = 0,
		giveatendround = false,
		awardexp = 100,
		textnotify = true,
	},

	{
		name = "cannibal",
		achievements_name = "Отличный ужин",
		desc = "Съесть 10 трупов за каннибала",
		image = "nextoren/achievements/ahive138.jpg",
		secret = false,
		countable = true,
		countnum = 10,
		giveatendround = false,
		awardexp = 100,
		textnotify = false
	},

	{
		name = "scp914",
		achievements_name = "Колесо фортуны",
		desc = "Получить карту O5 в SCP-914",
		image = "nextoren/achievements/ahive43.jpg",
		secret = false,
		countable = false,
		countnum = 0,
		giveatendround = false,
		awardexp = 100,
		textnotify = true,
	},
	{
		name = "scp914burger",
		achievements_name = "Какой интересный бутик",
		desc = "Превратите труп в бургер в SCP-914",
		image = "nextoren/achievements/ahive43.jpg",
		secret = true,
		countable = false,
		countnum = 0,
		giveatendround = false,
		awardexp = 100,
		textnotify = true,
	},

	{
		name = "radioactive",
		achievements_name = "Это было в 86…",
		desc = "выпить радиоактивный дадо",
		image = "nextoren/achievements/ahive25.jpg",
		secret = false,
		countable = false,
		countnum = 0,
		giveatendround = false,
		awardexp = 100,
		textnotify = true,
	},

	{
		name = "spawn_scp",
		achievements_name = "Жертва экспериментов",
		desc = "Стать SCP",
		image = "nextoren/achievements/ahive61.jpg",
		secret = false,
		countable = false,
		countnum = 0,
		giveatendround = false,
		awardexp = 100,
		textnotify = true,
	},

	{
		name = "death",
		achievements_name = "I won’t be coming home",
		desc = "Принять свою смерть",
		image = "nextoren/achievements/ahive26.jpg",
		secret = false,
		countable = false,
		countnum = 0,
		giveatendround = false,
		awardexp = 100,
		textnotify = true,
	},

	{
		name = "clocker",
		achievements_name = "Фишер мог бы мной гордиться",
		desc = "Стать Устранителем ОНП",
		image = "nextoren/achievements/ahive72.jpg",
		secret = false,
		countable = false,
		countnum = 0,
		giveatendround = false,
		awardexp = 100,
		textnotify = true,
	},

	{
		name = "backstab",
		achievements_name = "Привет от сантехника",
		desc = "Ударить человека холодным оружием по спине",
		image = "nextoren/achievements/ahive69.jpg",
		secret = false,
		countable = false,
		countnum = 0,
		giveatendround = false,
		awardexp = 100,
		textnotify = true,
	},

	{
		name = "mtfagent",
		achievements_name = "Большой брат следит за тобой",
		desc = "выследить шпиона за агента вб",
		image = "nextoren/achievements/ahive128.jpg",
		secret = false,
		countable = false,
		countnum = 0,
		giveatendround = false,
		awardexp = 100,
		textnotify = true,
	},

	{
		name = "runbitch",
		achievements_name = "Беги сука",
		desc = "сбежать за 5 секунд до взрыва",
		image = "nextoren/achievements/ahive46.jpg",
		secret = false,
		countable = false,
		countnum = 0,
		giveatendround = false,
		awardexp = 100,
		textnotify = true,
	},

	{
		name = "zov",
		achievements_name = "Своих не бросаем",
		desc = "Спасите SCP 079 от взрыва",
		image = "nextoren/achievements/ahive46.jpg",
		secret = false,
		countable = false,
		countnum = 0,
		giveatendround = false,
		awardexp = 100,
		textnotify = true,
	},

	{
		name = "protocol",
		achievements_name = "Протокол Eisenskorpion",
		desc = "вызвать поддержку за диспетчера или гк",
		image = "nextoren/achievements/ahive132.jpg",
		secret = false,
		countable = false,
		countnum = 0,
		giveatendround = false,
		awardexp = 100,
		textnotify = true,
	},

	{
		name = "weaponry",
		achievements_name = "Воины к оружию",
		desc = "играя за сб получить снаряжение в офисной зоне",
		image = "nextoren/achievements/ahive123.jpg",
		secret = false,
		countable = false,
		countnum = 0,
		giveatendround = false,
		awardexp = 100,
		textnotify = true,
	},

	{
		name = "armor",
		achievements_name = "Пригодиться или нет, решать уже потом",
		desc = "одеть каску и бронежилет за ученого или класс-д",
		image = "nextoren/achievements/ahive88.jpg",
		secret = false,
		countable = false,
		countnum = 0,
		giveatendround = false,
		awardexp = 100,
		textnotify = true,
	},

	{
		name = "deffib",
		achievements_name = "Своих не бросаем",
		desc = "воскресить человека деффибрилятором",
		image = "nextoren/achievements/ahive127.jpg",
		secret = false,
		countable = false,
		countnum = 0,
		giveatendround = false,
		awardexp = 100,
		textnotify = true,
	},

}