ENT.Type = "anim"
ENT.Base = "base_anim"
ENT.AutomaticFrameAdvance = true
ENT.Model = "models/zerochain/props_christmas/snowballswep/zck_w_snowballswep.mdl"
ENT.Spawnable = false
ENT.AdminSpawnable = false
ENT.PrintName = "Snowball"
ENT.Category = "Zeros Snowball Swep"
ENT.RenderGroup = RENDERGROUP_OPAQUE
